//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale.Geographic.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vale.Geographic.Domain.Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe uma categoria válida..
        /// </summary>
        public static string AreaCategoryInvalid {
            get {
                return ResourceManager.GetString("AreaCategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da cor da área não pode ter mais que 255 caracteres..
        /// </summary>
        public static string AreaColorLength {
            get {
                return ResourceManager.GetString("AreaColorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação da area..
        /// </summary>
        public static string AreaCreatedAtRequired {
            get {
                return ResourceManager.GetString("AreaCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação da area..
        /// </summary>
        public static string AreaCreatedByRequired {
            get {
                return ResourceManager.GetString("AreaCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da area não pode ter mais do que 255 caracteres..
        /// </summary>
        public static string AreaDescriptionLength {
            get {
                return ResourceManager.GetString("AreaDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area existente..
        /// </summary>
        public static string AreaExisting {
            get {
                return ResourceManager.GetString("AreaExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da area.
        /// </summary>
        public static string AreaIdRequired {
            get {
                return ResourceManager.GetString("AreaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a ultima data de atualização da area..
        /// </summary>
        public static string AreaLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("AreaLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de atualização da area..
        /// </summary>
        public static string AreaLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("AreaLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe uma localização válida..
        /// </summary>
        public static string AreaLocationInvalid {
            get {
                return ResourceManager.GetString("AreaLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a localização da area..
        /// </summary>
        public static string AreaLocationRequired {
            get {
                return ResourceManager.GetString("AreaLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da area não pode ter mais do que 150 caracteres..
        /// </summary>
        public static string AreaNameLength {
            get {
                return ResourceManager.GetString("AreaNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o nome da area..
        /// </summary>
        public static string AreaNameRequired {
            get {
                return ResourceManager.GetString("AreaNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area não encontrada..
        /// </summary>
        public static string AreaNotFound {
            get {
                return ResourceManager.GetString("AreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status da area..
        /// </summary>
        public static string AreaStatusRequired {
            get {
                return ResourceManager.GetString("AreaStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação da auditoria..
        /// </summary>
        public static string AuditoryCreatedAtRequired {
            get {
                return ResourceManager.GetString("AuditoryCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação da auditoria..
        /// </summary>
        public static string AuditoryCreatedByRequired {
            get {
                return ResourceManager.GetString("AuditoryCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da  da auditoria..
        /// </summary>
        public static string AuditoryIdRequired {
            get {
                return ResourceManager.GetString("AuditoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a ultima data de atualização da auditoria..
        /// </summary>
        public static string AuditoryLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("AuditoryLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de atualização da auditoria..
        /// </summary>
        public static string AuditoryLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("AuditoryLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o novo valor..
        /// </summary>
        public static string AuditoryNewValueRequired {
            get {
                return ResourceManager.GetString("AuditoryNewValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o valor anterior..
        /// </summary>
        public static string AuditoryOldValueRequired {
            get {
                return ResourceManager.GetString("AuditoryOldValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status da auditoria..
        /// </summary>
        public static string AuditoryStatusRequired {
            get {
                return ResourceManager.GetString("AuditoryStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o tipo de auditoria..
        /// </summary>
        public static string AuditoryTypeRequired {
            get {
                return ResourceManager.GetString("AuditoryTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível atualizar a categoria de perímetro oficial..
        /// </summary>
        public static string CannotUpdateOficialPerimeterCategory {
            get {
                return ResourceManager.GetString("CannotUpdateOficialPerimeterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação da categoria..
        /// </summary>
        public static string CategoryCreatedAtRequired {
            get {
                return ResourceManager.GetString("CategoryCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação da categoria..
        /// </summary>
        public static string CategoryCreatedByRequired {
            get {
                return ResourceManager.GetString("CategoryCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da categoria..
        /// </summary>
        public static string CategoryIdRequired {
            get {
                return ResourceManager.GetString("CategoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a última data de atualização da categoria.
        /// </summary>
        public static string CategoryLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("CategoryLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de atualização da categoria..
        /// </summary>
        public static string CategoryLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("CategoryLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nome da categoria não pode ter mais do que 255 caracteres..
        /// </summary>
        public static string CategoryNameLength {
            get {
                return ResourceManager.GetString("CategoryNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a nome da categoria..
        /// </summary>
        public static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada..
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status da categoria..
        /// </summary>
        public static string CategoryStatusRequired {
            get {
                return ResourceManager.GetString("CategoryStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o tipo de categoria..
        /// </summary>
        public static string CategoryTypeRequired {
            get {
                return ResourceManager.GetString("CategoryTypeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ponto focal já cadastrado..
        /// </summary>
        public static string FocalPointAlreadyExists {
            get {
                return ResourceManager.GetString("FocalPointAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação do ponto focal..
        /// </summary>
        public static string FocalPointCreatedAtRequired {
            get {
                return ResourceManager.GetString("FocalPointCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação do ponto focal..
        /// </summary>
        public static string FocalPointCreatedByRequired {
            get {
                return ResourceManager.GetString("FocalPointCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID do ponto focal..
        /// </summary>
        public static string FocalPointIdRequired {
            get {
                return ResourceManager.GetString("FocalPointIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a última data de atualização do ponto focal..
        /// </summary>
        public static string FocalPointLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("FocalPointLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de atualização do ponto focal..
        /// </summary>
        public static string FocalPointLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("FocalPointLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matricula do ponto focal não pode ter mais do que 15 caracteres..
        /// </summary>
        public static string FocalPointMatriculaLength {
            get {
                return ResourceManager.GetString("FocalPointMatriculaLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a matricula do ponto focal..
        /// </summary>
        public static string FocalPointMatriculaRequired {
            get {
                return ResourceManager.GetString("FocalPointMatriculaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do ponto focal não pode ter mais do que 250 caracteres..
        /// </summary>
        public static string FocalPointNameLength {
            get {
                return ResourceManager.GetString("FocalPointNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a nome do ponto focal..
        /// </summary>
        public static string FocalPointNameRequired {
            get {
                return ResourceManager.GetString("FocalPointNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Focal não encontrado..
        /// </summary>
        public static string FocalPointNotFound {
            get {
                return ResourceManager.GetString("FocalPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do ponto focal não pode ter mais do que 50 caracteres..
        /// </summary>
        public static string FocalPointPhoneNumberLength {
            get {
                return ResourceManager.GetString("FocalPointPhoneNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status do ponto focal..
        /// </summary>
        public static string FocalPointStatusRequired {
            get {
                return ResourceManager.GetString("FocalPointStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe se a notifcação foi respondida.
        /// </summary>
        public static string NotificationAnswerAnsweredRequired {
            get {
                return ResourceManager.GetString("NotificationAnswerAnsweredRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o id do ponto focal .
        /// </summary>
        public static string NotificationAnswerFocalPointIdRequired {
            get {
                return ResourceManager.GetString("NotificationAnswerFocalPointIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o id da resposta.
        /// </summary>
        public static string NotificationAnswerIdRequired {
            get {
                return ResourceManager.GetString("NotificationAnswerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe  o id da notificação.
        /// </summary>
        public static string NotificationAnswerNotificationIdRequired {
            get {
                return ResourceManager.GetString("NotificationAnswerNotificationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe idade da pessoa..
        /// </summary>
        public static string PersonSampleAgeRequired {
            get {
                return ResourceManager.GetString("PersonSampleAgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de nascimento da pessoa..
        /// </summary>
        public static string PersonSampleDateBirthRequired {
            get {
                return ResourceManager.GetString("PersonSampleDateBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ter mais do que 50 caracters..
        /// </summary>
        public static string PersonSampleFirstNameLength {
            get {
                return ResourceManager.GetString("PersonSampleFirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o primeiro nome da pessoa..
        /// </summary>
        public static string PersonSampleFirstNameRequired {
            get {
                return ResourceManager.GetString("PersonSampleFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da pessoa..
        /// </summary>
        public static string PersonSampleIdRequired {
            get {
                return ResourceManager.GetString("PersonSampleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome não pode ter mais do que 50 caracters..
        /// </summary>
        public static string PersonSampleLastNameLength {
            get {
                return ResourceManager.GetString("PersonSampleLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o último nome da pessoa..
        /// </summary>
        public static string PersonSampleLastNameRequired {
            get {
                return ResourceManager.GetString("PersonSampleLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o tipo de pessoa..
        /// </summary>
        public static string PersonSampleTypeRequired {
            get {
                return ResourceManager.GetString("PersonSampleTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da area do ponto de interesse..
        /// </summary>
        public static string PointOfInterestAreaIdRequired {
            get {
                return ResourceManager.GetString("PointOfInterestAreaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe uma categoria válida..
        /// </summary>
        public static string PointOfInterestCategoryInvalid {
            get {
                return ResourceManager.GetString("PointOfInterestCategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação do ponto de interesse..
        /// </summary>
        public static string PointOfInterestCreatedAtRequired {
            get {
                return ResourceManager.GetString("PointOfInterestCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação do ponto de interesse..
        /// </summary>
        public static string PointOfInterestCreatedByRequired {
            get {
                return ResourceManager.GetString("PointOfInterestCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do ponto de interesse não pode ter mais do que 255 caracteres..
        /// </summary>
        public static string PointOfInterestDescriptionLength {
            get {
                return ResourceManager.GetString("PointOfInterestDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto de interesse existente..
        /// </summary>
        public static string PointOfInterestExisting {
            get {
                return ResourceManager.GetString("PointOfInterestExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do ícone do ponto de interesse não pode ter mais que 255 caracteres..
        /// </summary>
        public static string PointOfInterestIconLength {
            get {
                return ResourceManager.GetString("PointOfInterestIconLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID do ponto de interesse..
        /// </summary>
        public static string PointOfInterestIdRequired {
            get {
                return ResourceManager.GetString("PointOfInterestIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a ultima data de atualizaçãodo ponto de interesse..
        /// </summary>
        public static string PointOfInterestLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("PointOfInterestLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de atualização do ponto de interesse..
        /// </summary>
        public static string PointOfInterestLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("PointOfInterestLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe uma localização válida..
        /// </summary>
        public static string PointOfInterestLocationInvalid {
            get {
                return ResourceManager.GetString("PointOfInterestLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a localização do ponto de interesse..
        /// </summary>
        public static string PointOfInterestLocationRequired {
            get {
                return ResourceManager.GetString("PointOfInterestLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do ponto de interesse não pode ter mais do que 150 caracteres..
        /// </summary>
        public static string PointOfInterestNameLength {
            get {
                return ResourceManager.GetString("PointOfInterestNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o nome do ponto de interesse..
        /// </summary>
        public static string PointOfInterestNameRequired {
            get {
                return ResourceManager.GetString("PointOfInterestNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto de Interesse não encontrado..
        /// </summary>
        public static string PointOfInterestNotFound {
            get {
                return ResourceManager.GetString("PointOfInterestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status do ponto de interesse..
        /// </summary>
        public static string PointOfInterestStatusRequired {
            get {
                return ResourceManager.GetString("PointOfInterestStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da area da rota..
        /// </summary>
        public static string RouteAreaIdRequired {
            get {
                return ResourceManager.GetString("RouteAreaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação da rota..
        /// </summary>
        public static string RouteCreatedAtRequired {
            get {
                return ResourceManager.GetString("RouteCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação da rota..
        /// </summary>
        public static string RouteCreatedByRequired {
            get {
                return ResourceManager.GetString("RouteCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da rota não pode ter mais do que 255 caracteres..
        /// </summary>
        public static string RouteDescriptionLength {
            get {
                return ResourceManager.GetString("RouteDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da rota..
        /// </summary>
        public static string RouteIdRequired {
            get {
                return ResourceManager.GetString("RouteIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a ultima data de atualização da rota..
        /// </summary>
        public static string RouteLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("RouteLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de atualização da rota..
        /// </summary>
        public static string RouteLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("RouteLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe uma localização válida..
        /// </summary>
        public static string RouteLocationInvalid {
            get {
                return ResourceManager.GetString("RouteLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a localização da rota..
        /// </summary>
        public static string RouteLocationRequired {
            get {
                return ResourceManager.GetString("RouteLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do ponto de interesse não pode ter mais do que 150 caracteres..
        /// </summary>
        public static string RouteNameLength {
            get {
                return ResourceManager.GetString("RouteNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o nome do ponto de interesse..
        /// </summary>
        public static string RouteNameRequired {
            get {
                return ResourceManager.GetString("RouteNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota não encontrada..
        /// </summary>
        public static string RouteNotFound {
            get {
                return ResourceManager.GetString("RouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status da rota.
        /// </summary>
        public static string RouteStatusRequired {
            get {
                return ResourceManager.GetString("RouteStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da area do segmento..
        /// </summary>
        public static string SegmentAreaIdRequired {
            get {
                return ResourceManager.GetString("SegmentAreaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação do segmento..
        /// </summary>
        public static string SegmentCreatedAtRequired {
            get {
                return ResourceManager.GetString("SegmentCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação do segmento..
        /// </summary>
        public static string SegmentCreatedByRequired {
            get {
                return ResourceManager.GetString("SegmentCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do segmento não pode ter mais do que 255 caracteres..
        /// </summary>
        public static string SegmentDescriptionLength {
            get {
                return ResourceManager.GetString("SegmentDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID do segmento..
        /// </summary>
        public static string SegmentIdRequired {
            get {
                return ResourceManager.GetString("SegmentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a ultima data de atualização do segmento..
        /// </summary>
        public static string SegmentLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("SegmentLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de atualização do segmento..
        /// </summary>
        public static string SegmentLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("SegmentLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe uma localização válida..
        /// </summary>
        public static string SegmentLocationInvalid {
            get {
                return ResourceManager.GetString("SegmentLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a localizaçãodo segmento..
        /// </summary>
        public static string SegmentLocationRequired {
            get {
                return ResourceManager.GetString("SegmentLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do segmento não pode ter mais do que 150 caracteres..
        /// </summary>
        public static string SegmentNameLength {
            get {
                return ResourceManager.GetString("SegmentNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o nome do segmento..
        /// </summary>
        public static string SegmentNameRequired {
            get {
                return ResourceManager.GetString("SegmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmento não encontrado..
        /// </summary>
        public static string SegmentNotFound {
            get {
                return ResourceManager.GetString("SegmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da rota do segmento..
        /// </summary>
        public static string SegmentRouteIdRequired {
            get {
                return ResourceManager.GetString("SegmentRouteIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status do segmento..
        /// </summary>
        public static string SegmentStatusRequired {
            get {
                return ResourceManager.GetString("SegmentStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de criação do usuário..
        /// </summary>
        public static string UserCreatedAtRequired {
            get {
                return ResourceManager.GetString("UserCreatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuario de criação do usuário..
        /// </summary>
        public static string UserCreatedByRequired {
            get {
                return ResourceManager.GetString("UserCreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do usuário não pode ter mais do que 100 caracteres..
        /// </summary>
        public static string UserEmailLength {
            get {
                return ResourceManager.GetString("UserEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID do usuário..
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a última data de atualização do usuário..
        /// </summary>
        public static string UserLastUpdatedAtRequired {
            get {
                return ResourceManager.GetString("UserLastUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o usuário de atualização do usuário..
        /// </summary>
        public static string UserLastUpdatedByRequired {
            get {
                return ResourceManager.GetString("UserLastUpdatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matricula do usuário não pode ter mais do que 15 caracteres..
        /// </summary>
        public static string UserMatriculaLength {
            get {
                return ResourceManager.GetString("UserMatriculaLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a matricula do usuário..
        /// </summary>
        public static string UserMatriculaRequired {
            get {
                return ResourceManager.GetString("UserMatriculaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário não pode ter mais do que 250 caracteres..
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a nome do usuário..
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o perfil do usuário..
        /// </summary>
        public static string UserProfileRequired {
            get {
                return ResourceManager.GetString("UserProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o status do usuário.
        /// </summary>
        public static string UserStatusRequired {
            get {
                return ResourceManager.GetString("UserStatusRequired", resourceCulture);
            }
        }
    }
}
