//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale.Geographic.Domain.Resources
{
    using System;
    using System.Diagnostics.CodeAnalysis;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [ExcludeFromCodeCoverage]
    public class Validations
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vale.Geographic.Domain.Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de nascimento da pessoa..
        /// </summary>
        public static string PersonSampleAgeRequired
        {
            get
            {
                return ResourceManager.GetString("PersonSampleAgeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a data de nascimento da pessoa..
        /// </summary>
        public static string PersonSampleDateBirthRequired
        {
            get
            {
                return ResourceManager.GetString("PersonSampleDateBirthRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ter mais do que 50 caracters..
        /// </summary>
        public static string PersonSampleFirstNameLength
        {
            get
            {
                return ResourceManager.GetString("PersonSampleFirstNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o primeiro nome da pessoa..
        /// </summary>
        public static string PersonSampleFirstNameRequired
        {
            get
            {
                return ResourceManager.GetString("PersonSampleFirstNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o ID da pessoa..
        /// </summary>
        public static string PersonSampleIdRequired
        {
            get
            {
                return ResourceManager.GetString("PersonSampleIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O sobrenome não pode ter mais do que 50 caracters..
        /// </summary>
        public static string PersonSampleLastNameLength
        {
            get
            {
                return ResourceManager.GetString("PersonSampleLastNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o último nome da pessoa..
        /// </summary>
        public static string PersonSampleLastNameRequired
        {
            get
            {
                return ResourceManager.GetString("PersonSampleLastNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o tipo de pessoa..
        /// </summary>
        public static string PersonSampleTypeRequired
        {
            get
            {
                return ResourceManager.GetString("PersonSampleTypeRequired", resourceCulture);
            }
        }
    }
}
